# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dthora', models.DateTimeField(auto_now=True, verbose_name='Data e hora da inclusão')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('texto', models.TextField()),
                ('imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[480, 375], upload_to='dicas')),
            ],
        ),
        migrations.CreateModel(
            name='DicasCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='dicas',
            name='idCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DicasCategorias'),
        ),
    ]
