# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dicas',
            new_name='Dica',
        ),
        migrations.RenameModel(
            old_name='DicasCategorias',
            new_name='DicasCategoria',
        ),
    ]
