# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170928_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[300, 300], upload_to='associados', verbose_name='foto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dicascategoria',
            options={'verbose_name': 'categoria de dicas', 'verbose_name_plural': 'categorias de dicas'},
        ),
        migrations.AlterModelOptions(
            name='noticiascategoria',
            options={'verbose_name': 'categoria de notícias', 'verbose_name_plural': 'categorias de notícias'},
        ),
        migrations.AlterField(
            model_name='dica',
            name='dthora',
            field=models.DateTimeField(auto_now=True, verbose_name='data e hora da inclusão'),
        ),
        migrations.AlterField(
            model_name='dica',
            name='idCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DicasCategoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='dica',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='dicascategoria',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='dthora',
            field=models.DateTimeField(auto_now=True, verbose_name='data e hora da inclusão'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='idCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NoticiasCategoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='noticiascategoria',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='categoria'),
        ),
    ]
