# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170928_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[780, 600], upload_to='memorias')),
            ],
        ),
    ]
