# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_memoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoria',
            options={'verbose_name': 'memória'},
        ),
        migrations.AlterField(
            model_name='memoria',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
