# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171004_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='NossaHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo_cabecalho', models.CharField(max_length=200, verbose_name='subtítulo')),
                ('imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[1920, 790], upload_to='quem_somos')),
                ('texto_destaque', models.TextField(max_length=500)),
                ('titulo_historia', models.CharField(max_length=200)),
                ('historia', models.TextField()),
            ],
            options={
                'verbose_name': 'nossa história',
                'verbose_name_plural': 'nossa história',
            },
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='subtitulo',
            field=models.CharField(max_length=200, verbose_name='subtítulo'),
        ),
    ]
