# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171005_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('descricao', models.CharField(max_length=100, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'link útil',
                'verbose_name_plural': 'links úteis',
            },
        ),
    ]
