# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo_cabecalho', models.CharField(max_length=200, verbose_name='subtítulo')),
                ('imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[1920, 790], upload_to='quem_somos')),
                ('titulo_rodape', models.CharField(max_length=200)),
                ('texto_rodape_1', models.TextField()),
                ('texto_rodape_2', models.TextField()),
                ('texto_rodape_3', models.TextField()),
            ],
            options={
                'verbose_name': 'link útil',
                'verbose_name_plural': 'links úteis',
            },
        ),
    ]
