# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171006_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='facebook',
            field=models.URLField(default='http://facebook.com.br/ascanavigv'),
            preserve_default=False,
        ),
    ]
