# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contato_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='coleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Dica', verbose_name='Dias e horários de coleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='dicas_reciclagem',
            field=models.URLField(default='http://127.0.0.1:8000/dicas', verbose_name='Dicas sobre reciclagem'),
            preserve_default=False,
        ),
    ]
