# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171010_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto_destaque',
            field=models.TextField(default='texto destacado ;-)', max_length=500, verbose_name='texto de destaque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dica',
            name='texto_destaque',
            field=models.TextField(max_length=500, verbose_name='texto de destaque'),
        ),
    ]
