# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171010_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_titulo', models.CharField(max_length=100, verbose_name='título principal')),
                ('principal_subtitulo', models.CharField(max_length=100, verbose_name='subtítulo principal')),
                ('principal_imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[1920, 715], upload_to='index', verbose_name='imagem principal')),
                ('dica_titulo', models.CharField(max_length=100, verbose_name='título da dica')),
                ('dica1_imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[780, 780], upload_to='index', verbose_name='imagem da dica da esquerda')),
                ('dica2_imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[780, 780], upload_to='index', verbose_name='imagem da dica do meio')),
                ('dica3_imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[780, 780], upload_to='index', verbose_name='imagem da dica da direita')),
                ('contribuir_titulo', models.CharField(max_length=100, verbose_name='texto sobre contribuir')),
                ('contribuir_imagem', django_resized.forms.ResizedImageField(crop=None, keep_meta=False, quality=75, size=[1920, 1200], upload_to='index', verbose_name='imagem sobre contribuir')),
                ('contrinuir_botao', models.CharField(max_length=100, verbose_name='texto do botão sobre contribuir')),
                ('contribuir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contribuir', verbose_name='link do botão sobre contribuir')),
                ('dica1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dica1_id', to='core.Dica', verbose_name='dica da esquerda')),
                ('dica2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dica2_id', to='core.Dica', verbose_name='dica do meio')),
                ('dica3_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dica3_id', to='core.Dica', verbose_name='dica da direita')),
            ],
            options={
                'verbose_name': 'início',
                'verbose_name_plural': 'início',
            },
        ),
    ]
