# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='contribuir_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContribuirItem', verbose_name='link do botão sobre contribuir'),
        ),
    ]
