# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20171012_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='contribuir_id',
        ),
    ]
