# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_index_contribuir_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='dicas_reciclagem',
        ),
    ]
